name = "connexions"
pages_build_output_dir = "src"
compatibility_date = "2026-09-05"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true

[[d1_databases]]
binding = "DB"
database_name = "connexions"
database_id = "4fbf6d1e-ca1d-4db9-ae65-0c5e21f2712d"
